spring:
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: ${CLIENT_ID}
            clientSecret: ${CLIENT_SECRET}

  kafka:
    topic: "employee-events"
    bootstrap-servers: localhost:29092
    producer:
      bootstrap-servers:
        - localhost:9092,localhost:9093,localhost:9094
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    admin:
      properties:
        bootstrap-servers: localhost:9092,localhost:9093,localhost:9094
